[package]
name = "no-defaults-fuzz"
version = "0.0.0"
publish = false
license = "MIT"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
no-defaults = { path = ".." }

[workspace]
members = ["."]

[[bin]]
name = "source-analysis"
path = "fuzz_targets/source-analysis.rs"
test = false
doc = false
bench = false

[[bin]]
name = "source-deletions"
path = "fuzz_targets/source-deletions.rs"
test = false
doc = false
bench = false
